version: "3"

services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - "5433:5432"
    volumes:
      - ~/DockerVolumes/blogify/postgres:/var/lib/postgresql/data
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    environment:
      - POSTGRES_PASSWORD=q
      - TZ=Europe/Istanbul
      - LANG=tr_TR.utf8
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=tr-TR
    restart: always

